//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mandelbrot1.rc
//
#define IDD_FORMVIEW                    101
#define IDR_MENU1                       101
#define IDC_VIEW                        1000
#define IDC_COORDS                      1002
#define IDM_QUIT                        40001
#define IDM_RESTART                     40002
#define IDM_REALIGN                     40003
#define IDM_ZOOMO2                      40005
#define IDM_ZOOMO5                      40006
#define IDM_ZOOMO10                     40007
#define IDM_UNDO                        40008
#define IDM_RES25                       40010
#define IDM_RES50                       40011
#define IDM_RES100                      40012
#define IDM_RES200                      40013
#define IDM_RES400                      40014
#define IDM_RES800                      40015
#define IDM_RES1600                     40016
#define IDM_RES3200                     40017
#define IDM_RES6400                     40018
#define IDM_RES12800                    40019
#define IDM_RES25600                    40020
#define IDM_BLUE                        40022
#define IDM_RED                         40023
#define IDM_GREEN                       40024
#define IDM_YELLOW                      40025
#define IDM_GRAY                        40026
#define IDM_RAINBOW                     40027
#define IDM_WEB                         40028
#define IDM_WEB2                        40029
#define IDM_RESA                        40030
#define IDM_RESB                        40031
#define IDM_RESC                        40032
#define IDM_RESD                        40033
#define IDM_RESE                        40034
#define IDM_RESF                        40035

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40036
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
