//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ComplexGraph.rc
//
#define IDD_MAIN                        101
#define IDR_MENU1                       101
#define IDC_VIEW2                       1000
#define IDC_VIEW1                       1000
#define IDC_VIEW3                       1001
#define IDC_EQUATION                    1003
#define IDC_CALC                        1004
#define IDC_VIEW1ZOOMOUT                1005
#define IDC_VIEW1ZOOMRESET              1006
#define IDC_VIEW1ZOOMIN                 1007
#define IDC_VIEW2ZOOMOUT                1008
#define IDC_VIEW2ZOOMRESET              1009
#define IDC_VIEW2ZOOMIN                 1010
#define IDC_LINE_EDIT                   1011
#define IDC_ERASE_USER                  1012
#define ID_FILE_EXIT                    40001
#define ID_GRAPHTYPE_BLANKET            40002
#define ID_GRAPHTYPE_LINE               40003
#define ID_GRAPHTYPE_FREEDRAW           40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
